repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-xml
    - id: check-added-large-files
    - id: check-merge-conflict

#- repo: https://github.com/codespell-project/codespell
#  rev: v2.2.4
#  hooks:
#  - id: codespell
