title: Infotiv portfolio of projects
description: Welcome to the online portfolio of Infotiv research team
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://infotiv-research.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: infotiv #if your site has a twitter account, enter it here

# Author Settings
author: Infotiv portfolio of projects # add your name
author-img: home.png # add your photo
about-author: Infotiv works globally with some of the world’s leading brands as an operative partner. We supply consultancy services and the answers that promote development, sales and use of technical products.
social-twitter: infotiv # add your Twitter handle
social-facebook: infotiv.se # add your Facebook handle
social-github: infotiv-research # add your Github handle
social-linkedin: infotiv # add your Linkedin handle
# social-email: hamid[dot]ebadi(a)gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
